prometheus:
  url: http://localhost:9090

train:
  path: ./tmp/train

  start_at: 2024-10-14T04:06:22Z
  end_at:   2024-10-14T04:15:24Z
  step: 1s

  vars:
    rate: 120s

  pipelines: #todo: rename as pipelines
    - name: node-cpu
      features:
        node_cpu_time: |
          sum(
            rate( node_cpu_seconds_total{job="vm-node-exporter", mode!="idle"}[${rate}])
          ) * 1000

    - name: kepler-vm-cpu
      features:
        cpu_time: sum(rate(kepler_process_bpf_cpu_time_ms_total{job="vm", pid!="1"}[${rate}]))
        page_cache_hits: sum(rate(kepler_process_bpf_page_cache_hit_total{job="vm"}[${rate}]))

  target: sum(rate(kepler_vm_package_joules_total{job="metal"}[${rate}]))

  # for each group create
  models:
    xgboost:
      objective: "reg:squarederror"
      random_state: 42
    linear:
    polynomial:
      degree: 2
