prometheus:
  url: http://localhost:9090

train:
  path: ./tmp/train

  start_at: 2024-10-08T23:03:16Z
  end_at:   2024-10-08T23:12:18Z
  step: 1s

  vars:
    - rate: 10s

  groups:
    - name: node-cpu
      features:
        node_cpu_time: |
          sum(
            rate( node_cpu_seconds_total{job="vm-node-exporter", mode=~"user"}[10s] )
          ) * 1000
        cpus: 2

    # - name: kepler-metal-cpu
    #   features:
    #     cpu_time: sum(rate(kepler_vm_bpf_cpu_time_ms_total{job="metal"}[10s]))
    #     page_cache_hits: sum(rate(kepler_vm_bpf_page_cache_hit_total{job="metal"}[10s]))
    #     cpus: 2

    - name: kepler-vm-cpu
      features:
        cpu_time: sum(rate(kepler_process_bpf_cpu_time_ms_total{job="vm"}[10s]))
        page_cache_hits: sum(rate(kepler_process_bpf_page_cache_hit_total{job="vm"}[10s]))
        cpus: 2

  target: sum(rate(kepler_vm_package_joules_total{job="metal"}[10s]))
  # target: sum(rate(kepler_process_package_joules_total{pid="3438583", job="metal"}[20s]))

  # for each group create  
  models:
    xgboost:
      objective: "reg:squarederror"
      random_state: 42
    linear:
    polynomial:
      degree: 2
