prometheus:
  url: http://localhost:9090

train:
  path: ./tmp/train

  start_at: 2024-10-14T04:06:22Z
  end_at:   2024-10-14T04:15:24Z
  step: 1s

  vars:
    - learn_rate: 10s
    - run_rate: 10s

  groups: #todo: rename as pipelines
    - name: node-cpu
      features:
        node_cpu_time: |
          sum( rate( node_cpu_seconds_total{job="vm-node-exporter", mode!="idle"}[10s])) * 1000

    - name: kepler-vm-cpu
      features:
        cpu_time: sum(rate(kepler_process_bpf_cpu_time_ms_total{job="vm", pid!="1"}[10s]))
        page_cache_hits: sum(rate(kepler_process_bpf_page_cache_hit_total{job="vm"}[10s]))

    # - name: kepler-metal-cpu
    #   features:
    #     cpu_time: sum(rate(kepler_vm_bpf_cpu_time_ms_total{job="metal"}[10s]))
    #     page_cache_hits: sum(rate(kepler_vm_bpf_page_cache_hit_total{job="metal"}[10s]))


  target: sum(rate(kepler_vm_package_joules_total{job="metal"}[10s]))

  # for each group create  
  models:
    xgboost:
      objective: "reg:squarederror"
      random_state: 42
    linear:
    polynomial:
      degree: 2
