scrape_configs:
  - job_name: vm
    static_configs:
      - targets: [vm:9100]

  - job_name: vm-node-exporter
    static_configs:
      - targets: [vm:9800]



  # differentiate between vm and metal node-exporter
  - job_name: metal-node-exporter
    static_configs:
      - targets: [node-exporter:9100]

  - job_name: metal
    static_configs:
      - targets: [kepler-metal:8888]

  - job_name: scaphandre
    static_configs:
      - targets: [scaphandre:8080]
